services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop_be_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    networks:
      - shop_be_net

  nginx:
    image: nginx:1.27-alpine
    container_name: shop_be_nginx
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - shop_be_net

  db:
    image: mysql:8.0
    container_name: shop_be_db
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - shop_db_data:/var/lib/mysql
    networks:
      - shop_be_net

  redis:
    image: redis:7-alpine
    container_name: shop_be_redis
    ports:
      - "6380:6379"
    networks:
      - shop_be_net

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop_be_queue
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - db
      - redis
    command: php artisan queue:work --sleep=1 --tries=3 --timeout=120
    networks:
      - shop_be_net

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop_be_scheduler
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - db
      - redis
    command: sh -lc "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    networks:
      - shop_be_net

networks:
  shop_be_net:

volumes:
  shop_db_data:
